#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhongTro")]
	public partial class PhongTroDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCuocPhi(CuocPhi instance);
    partial void UpdateCuocPhi(CuocPhi instance);
    partial void DeleteCuocPhi(CuocPhi instance);
    partial void InsertThuePhong(ThuePhong instance);
    partial void UpdateThuePhong(ThuePhong instance);
    partial void DeleteThuePhong(ThuePhong instance);
    partial void InsertChiSoThang(ChiSoThang instance);
    partial void UpdateChiSoThang(ChiSoThang instance);
    partial void DeleteChiSoThang(ChiSoThang instance);
    partial void InsertChuPhong(ChuPhong instance);
    partial void UpdateChuPhong(ChuPhong instance);
    partial void DeleteChuPhong(ChuPhong instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertMauHopDong(MauHopDong instance);
    partial void UpdateMauHopDong(MauHopDong instance);
    partial void DeleteMauHopDong(MauHopDong instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertThanhToan(ThanhToan instance);
    partial void UpdateThanhToan(ThanhToan instance);
    partial void DeleteThanhToan(ThanhToan instance);
    partial void InsertChiuCuocPhi(ChiuCuocPhi instance);
    partial void UpdateChiuCuocPhi(ChiuCuocPhi instance);
    partial void DeleteChiuCuocPhi(ChiuCuocPhi instance);
    partial void InsertHopDong(HopDong instance);
    partial void UpdateHopDong(HopDong instance);
    partial void DeleteHopDong(HopDong instance);
    partial void InsertKhach(Khach instance);
    partial void UpdateKhach(Khach instance);
    partial void DeleteKhach(Khach instance);
    #endregion
		
		public PhongTroDBDataContext() : 
				base(global::DAL.Properties.Settings.Default.PhongTroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PhongTroDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhongTroDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhongTroDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PhongTroDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CuocPhi> CuocPhis
		{
			get
			{
				return this.GetTable<CuocPhi>();
			}
		}
		
		public System.Data.Linq.Table<ThuePhong> ThuePhongs
		{
			get
			{
				return this.GetTable<ThuePhong>();
			}
		}
		
		public System.Data.Linq.Table<ChiSoThang> ChiSoThangs
		{
			get
			{
				return this.GetTable<ChiSoThang>();
			}
		}
		
		public System.Data.Linq.Table<ChuPhong> ChuPhongs
		{
			get
			{
				return this.GetTable<ChuPhong>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<MauHopDong> MauHopDongs
		{
			get
			{
				return this.GetTable<MauHopDong>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<ThanhToan> ThanhToans
		{
			get
			{
				return this.GetTable<ThanhToan>();
			}
		}
		
		public System.Data.Linq.Table<ChiuCuocPhi> ChiuCuocPhis
		{
			get
			{
				return this.GetTable<ChiuCuocPhi>();
			}
		}
		
		public System.Data.Linq.Table<HopDong> HopDongs
		{
			get
			{
				return this.GetTable<HopDong>();
			}
		}
		
		public System.Data.Linq.Table<Khach> Khaches
		{
			get
			{
				return this.GetTable<Khach>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CuocPhi_Sua")]
		public int CuocPhi_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> macuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tencuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giacuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string thongtin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), macuocphi, tencuocphi, giacuocphi, thongtin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuePhong_Them")]
		public int ThuePhong_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> makhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> chuphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, makhach, mahopdong, chuphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CuocPhi_Them")]
		public int CuocPhi_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tencuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giacuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string thongtin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tencuocphi, giacuocphi, thongtin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CuocPhi_Xoa")]
		public int CuocPhi_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> macuocphi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), macuocphi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiSoThang_Sua")]
		public int ChiSoThang_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisodien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisonuoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, ngaycapnhat, chisodien, chisonuoc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiSoThang_Them")]
		public int ChiSoThang_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> sodien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> sonuoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, ngaycapnhat, sodien, sonuoc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiSoThang_Xoa")]
		public int ChiSoThang_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaycapnhat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, ngaycapnhat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChuPhong_Sua")]
		public int ChuPhong_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> machuphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenchuphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodinhdanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machuphong, tenchuphong, gioitinh, sodinhdanh, sodienthoai, diachi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChuPhong_Them")]
		public int ChuPhong_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenchuphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodinhdanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenchuphong, gioitinh, sodinhdanh, sodienthoai, diachi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChuPhong_Xoa")]
		public int ChuPhong_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> machuphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machuphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoaiPhong_Sua")]
		public int LoaiPhong_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> machuphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giathue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sokhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string thongtin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloaiphong, machuphong, tenloaiphong, giathue, sokhach, thongtin, diachi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoaiPhong_Them")]
		public int LoaiPhong_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> machuphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giathue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sokhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string thongtin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machuphong, tenloaiphong, giathue, sokhach, thongtin, diachi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LoaiPhong_Xoa")]
		public int LoaiPhong_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maloaiphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloaiphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_Sua")]
		public int NguoiDung_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manguoidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string tendangnhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string madangnhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> admin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manguoidung, tendangnhap, madangnhap, admin, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_Them")]
		public int NguoiDung_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string tendangnhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string madangnhap, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> admin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tendangnhap, madangnhap, admin, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NguoiDung_Xoa")]
		public int NguoiDung_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manguoidung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manguoidung);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Phong_Sua")]
		public int Phong_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tinhtrangphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, maloaiphong, tenphong, status, tinhtrangphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Phong_Them")]
		public int Phong_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maloaiphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tinhtrangphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloaiphong, tenphong, status, tinhtrangphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiuCuocPhi_Them")]
		public int ChiuCuocPhi_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> macuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahopdong, macuocphi, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HopDong_Sua")]
		public int HopDong_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaythue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaytra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaylamhopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> tiencoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giathue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisodien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisonuoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahopdong, ngaythue, ngaytra, ngaylamhopdong, tiencoc, giathue, chisodien, chisonuoc, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiuCuocPhi_Sua")]
		public int ChiuCuocPhi_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> macuocphi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahopdong, macuocphi, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiuCuocPhi_Xoa")]
		public int ChiuCuocPhi_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> macuocphi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahopdong, macuocphi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuePhong_Sua")]
		public int ThuePhong_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> makhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> chuphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, makhach, mahopdong, chuphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThuePhong_Xoa")]
		public int ThuePhong_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> makhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, makhach, mahopdong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HopDong_Them")]
		public int HopDong_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaythue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaytra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaylamhopdong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> tiencoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> giathue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisodien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> chisonuoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngaythue, ngaytra, ngaylamhopdong, tiencoc, giathue, chisodien, chisonuoc, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Khach_Sua")]
		public int Khach_Sua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> makhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodinhdanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string hinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> tinhtranghonnhan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> dangkytamtru)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makhach, tenkhach, ngaysinh, gioitinh, sodinhdanh, sodienthoai, diachi, hinh, tinhtranghonnhan, dangkytamtru);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Khach_Them")]
		public int Khach_Them([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenkhach, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(12)")] string sodinhdanh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(50)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string hinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> tinhtranghonnhan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> dangkytamtru)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenkhach, ngaysinh, gioitinh, sodinhdanh, sodienthoai, diachi, hinh, tinhtranghonnhan, dangkytamtru);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HopDong_Xoa")]
		public int HopDong_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> mahopdong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahopdong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Phong_Xoa")]
		public int Phong_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Khach_Xoa")]
		public int Khach_Xoa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> makhach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makhach);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuocPhi")]
	public partial class CuocPhi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCuocPhi;
		
		private string _TenCuocPhi;
		
		private decimal _GiaCuocPhi;
		
		private string _ThongTin;
		
		private EntitySet<ChiuCuocPhi> _ChiuCuocPhis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCuocPhiChanging(int value);
    partial void OnMaCuocPhiChanged();
    partial void OnTenCuocPhiChanging(string value);
    partial void OnTenCuocPhiChanged();
    partial void OnGiaCuocPhiChanging(decimal value);
    partial void OnGiaCuocPhiChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    #endregion
		
		public CuocPhi()
		{
			this._ChiuCuocPhis = new EntitySet<ChiuCuocPhi>(new Action<ChiuCuocPhi>(this.attach_ChiuCuocPhis), new Action<ChiuCuocPhi>(this.detach_ChiuCuocPhis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuocPhi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCuocPhi
		{
			get
			{
				return this._MaCuocPhi;
			}
			set
			{
				if ((this._MaCuocPhi != value))
				{
					this.OnMaCuocPhiChanging(value);
					this.SendPropertyChanging();
					this._MaCuocPhi = value;
					this.SendPropertyChanged("MaCuocPhi");
					this.OnMaCuocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCuocPhi", DbType="NVarChar(50)")]
		public string TenCuocPhi
		{
			get
			{
				return this._TenCuocPhi;
			}
			set
			{
				if ((this._TenCuocPhi != value))
				{
					this.OnTenCuocPhiChanging(value);
					this.SendPropertyChanging();
					this._TenCuocPhi = value;
					this.SendPropertyChanged("TenCuocPhi");
					this.OnTenCuocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaCuocPhi", DbType="Money NOT NULL")]
		public decimal GiaCuocPhi
		{
			get
			{
				return this._GiaCuocPhi;
			}
			set
			{
				if ((this._GiaCuocPhi != value))
				{
					this.OnGiaCuocPhiChanging(value);
					this.SendPropertyChanging();
					this._GiaCuocPhi = value;
					this.SendPropertyChanged("GiaCuocPhi");
					this.OnGiaCuocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(100)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuocPhi_ChiuCuocPhi", Storage="_ChiuCuocPhis", ThisKey="MaCuocPhi", OtherKey="MaCuocPhi")]
		public EntitySet<ChiuCuocPhi> ChiuCuocPhis
		{
			get
			{
				return this._ChiuCuocPhis;
			}
			set
			{
				this._ChiuCuocPhis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiuCuocPhis(ChiuCuocPhi entity)
		{
			this.SendPropertyChanging();
			entity.CuocPhi = this;
		}
		
		private void detach_ChiuCuocPhis(ChiuCuocPhi entity)
		{
			this.SendPropertyChanging();
			entity.CuocPhi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuePhong")]
	public partial class ThuePhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private long _MaKhach;
		
		private long _MaHopDong;
		
		private bool _ChuPhong;
		
		private EntityRef<Phong> _Phong;
		
		private EntityRef<HopDong> _HopDong;
		
		private EntityRef<Khach> _Khach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnMaKhachChanging(long value);
    partial void OnMaKhachChanged();
    partial void OnMaHopDongChanging(long value);
    partial void OnMaHopDongChanged();
    partial void OnChuPhongChanging(bool value);
    partial void OnChuPhongChanged();
    #endregion
		
		public ThuePhong()
		{
			this._Phong = default(EntityRef<Phong>);
			this._HopDong = default(EntityRef<HopDong>);
			this._Khach = default(EntityRef<Khach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhach", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaKhach
		{
			get
			{
				return this._MaKhach;
			}
			set
			{
				if ((this._MaKhach != value))
				{
					if (this._Khach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachChanging(value);
					this.SendPropertyChanging();
					this._MaKhach = value;
					this.SendPropertyChanged("MaKhach");
					this.OnMaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuPhong", DbType="Bit NOT NULL")]
		public bool ChuPhong
		{
			get
			{
				return this._ChuPhong;
			}
			set
			{
				if ((this._ChuPhong != value))
				{
					this.OnChuPhongChanging(value);
					this.SendPropertyChanging();
					this._ChuPhong = value;
					this.SendPropertyChanged("ChuPhong");
					this.OnChuPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ThuePhong", Storage="_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(int);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ThuePhong", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(long);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_ThuePhong", Storage="_Khach", ThisKey="MaKhach", OtherKey="MaKhach", IsForeignKey=true)]
		public Khach Khach
		{
			get
			{
				return this._Khach.Entity;
			}
			set
			{
				Khach previousValue = this._Khach.Entity;
				if (((previousValue != value) 
							|| (this._Khach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach.Entity = null;
						previousValue.ThuePhongs.Remove(this);
					}
					this._Khach.Entity = value;
					if ((value != null))
					{
						value.ThuePhongs.Add(this);
						this._MaKhach = value.MaKhach;
					}
					else
					{
						this._MaKhach = default(long);
					}
					this.SendPropertyChanged("Khach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiSoThang")]
	public partial class ChiSoThang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private System.DateTime _NgayCapNhat;
		
		private System.Nullable<long> _ChiSoDien;
		
		private System.Nullable<long> _ChiSoNuoc;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnNgayCapNhatChanging(System.DateTime value);
    partial void OnNgayCapNhatChanged();
    partial void OnChiSoDienChanging(System.Nullable<long> value);
    partial void OnChiSoDienChanged();
    partial void OnChiSoNuocChanging(System.Nullable<long> value);
    partial void OnChiSoNuocChanged();
    #endregion
		
		public ChiSoThang()
		{
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoDien", DbType="BigInt")]
		public System.Nullable<long> ChiSoDien
		{
			get
			{
				return this._ChiSoDien;
			}
			set
			{
				if ((this._ChiSoDien != value))
				{
					this.OnChiSoDienChanging(value);
					this.SendPropertyChanging();
					this._ChiSoDien = value;
					this.SendPropertyChanged("ChiSoDien");
					this.OnChiSoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoNuoc", DbType="BigInt")]
		public System.Nullable<long> ChiSoNuoc
		{
			get
			{
				return this._ChiSoNuoc;
			}
			set
			{
				if ((this._ChiSoNuoc != value))
				{
					this.OnChiSoNuocChanging(value);
					this.SendPropertyChanging();
					this._ChiSoNuoc = value;
					this.SendPropertyChanged("ChiSoNuoc");
					this.OnChiSoNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiSoThang", Storage="_Phong", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.ChiSoThangs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.ChiSoThangs.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(int);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuPhong")]
	public partial class ChuPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuPhong;
		
		private string _TenChuPhong;
		
		private bool _GioiTinh;
		
		private string _SoDinhDanh;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private EntitySet<LoaiPhong> _LoaiPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuPhongChanging(int value);
    partial void OnMaChuPhongChanged();
    partial void OnTenChuPhongChanging(string value);
    partial void OnTenChuPhongChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnSoDinhDanhChanging(string value);
    partial void OnSoDinhDanhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public ChuPhong()
		{
			this._LoaiPhongs = new EntitySet<LoaiPhong>(new Action<LoaiPhong>(this.attach_LoaiPhongs), new Action<LoaiPhong>(this.detach_LoaiPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChuPhong
		{
			get
			{
				return this._MaChuPhong;
			}
			set
			{
				if ((this._MaChuPhong != value))
				{
					this.OnMaChuPhongChanging(value);
					this.SendPropertyChanging();
					this._MaChuPhong = value;
					this.SendPropertyChanged("MaChuPhong");
					this.OnMaChuPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuPhong", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenChuPhong
		{
			get
			{
				return this._TenChuPhong;
			}
			set
			{
				if ((this._TenChuPhong != value))
				{
					this.OnTenChuPhongChanging(value);
					this.SendPropertyChanging();
					this._TenChuPhong = value;
					this.SendPropertyChanged("TenChuPhong");
					this.OnTenChuPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDinhDanh", DbType="NChar(12) NOT NULL", CanBeNull=false)]
		public string SoDinhDanh
		{
			get
			{
				return this._SoDinhDanh;
			}
			set
			{
				if ((this._SoDinhDanh != value))
				{
					this.OnSoDinhDanhChanging(value);
					this.SendPropertyChanging();
					this._SoDinhDanh = value;
					this.SendPropertyChanged("SoDinhDanh");
					this.OnSoDinhDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuPhong_LoaiPhong", Storage="_LoaiPhongs", ThisKey="MaChuPhong", OtherKey="MaChuPhong")]
		public EntitySet<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this._LoaiPhongs;
			}
			set
			{
				this._LoaiPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LoaiPhongs(LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.ChuPhong = this;
		}
		
		private void detach_LoaiPhongs(LoaiPhong entity)
		{
			this.SendPropertyChanging();
			entity.ChuPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiPhong;
		
		private int _MaChuPhong;
		
		private string _TenLoaiPhong;
		
		private System.Nullable<decimal> _GiaThue;
		
		private System.Nullable<int> _SoKhach;
		
		private string _ThongTin;
		
		private string _DiaChi;
		
		private EntitySet<Phong> _Phongs;
		
		private EntityRef<ChuPhong> _ChuPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnMaChuPhongChanging(int value);
    partial void OnMaChuPhongChanged();
    partial void OnTenLoaiPhongChanging(string value);
    partial void OnTenLoaiPhongChanged();
    partial void OnGiaThueChanging(System.Nullable<decimal> value);
    partial void OnGiaThueChanged();
    partial void OnSoKhachChanging(System.Nullable<int> value);
    partial void OnSoKhachChanged();
    partial void OnThongTinChanging(string value);
    partial void OnThongTinChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			this._ChuPhong = default(EntityRef<ChuPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuPhong", DbType="Int NOT NULL")]
		public int MaChuPhong
		{
			get
			{
				return this._MaChuPhong;
			}
			set
			{
				if ((this._MaChuPhong != value))
				{
					if (this._ChuPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuPhongChanging(value);
					this.SendPropertyChanging();
					this._MaChuPhong = value;
					this.SendPropertyChanged("MaChuPhong");
					this.OnMaChuPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiPhong", DbType="NVarChar(50)")]
		public string TenLoaiPhong
		{
			get
			{
				return this._TenLoaiPhong;
			}
			set
			{
				if ((this._TenLoaiPhong != value))
				{
					this.OnTenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiPhong = value;
					this.SendPropertyChanged("TenLoaiPhong");
					this.OnTenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Money")]
		public System.Nullable<decimal> GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoKhach", DbType="Int")]
		public System.Nullable<int> SoKhach
		{
			get
			{
				return this._SoKhach;
			}
			set
			{
				if ((this._SoKhach != value))
				{
					this.OnSoKhachChanging(value);
					this.SendPropertyChanging();
					this._SoKhach = value;
					this.SendPropertyChanged("SoKhach");
					this.OnSoKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTin", DbType="NVarChar(1000)")]
		public string ThongTin
		{
			get
			{
				return this._ThongTin;
			}
			set
			{
				if ((this._ThongTin != value))
				{
					this.OnThongTinChanging(value);
					this.SendPropertyChanging();
					this._ThongTin = value;
					this.SendPropertyChanged("ThongTin");
					this.OnThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_Phongs", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuPhong_LoaiPhong", Storage="_ChuPhong", ThisKey="MaChuPhong", OtherKey="MaChuPhong", IsForeignKey=true)]
		public ChuPhong ChuPhong
		{
			get
			{
				return this._ChuPhong.Entity;
			}
			set
			{
				ChuPhong previousValue = this._ChuPhong.Entity;
				if (((previousValue != value) 
							|| (this._ChuPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuPhong.Entity = null;
						previousValue.LoaiPhongs.Remove(this);
					}
					this._ChuPhong.Entity = value;
					if ((value != null))
					{
						value.LoaiPhongs.Add(this);
						this._MaChuPhong = value.MaChuPhong;
					}
					else
					{
						this._MaChuPhong = default(int);
					}
					this.SendPropertyChanged("ChuPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MauHopDong")]
	public partial class MauHopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMauThongTin;
		
		private string _TenMauThongTin;
		
		private string _ThongTinTrenHopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMauThongTinChanging(int value);
    partial void OnMaMauThongTinChanged();
    partial void OnTenMauThongTinChanging(string value);
    partial void OnTenMauThongTinChanged();
    partial void OnThongTinTrenHopDongChanging(string value);
    partial void OnThongTinTrenHopDongChanged();
    #endregion
		
		public MauHopDong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMauThongTin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMauThongTin
		{
			get
			{
				return this._MaMauThongTin;
			}
			set
			{
				if ((this._MaMauThongTin != value))
				{
					this.OnMaMauThongTinChanging(value);
					this.SendPropertyChanging();
					this._MaMauThongTin = value;
					this.SendPropertyChanged("MaMauThongTin");
					this.OnMaMauThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMauThongTin", DbType="NVarChar(100)")]
		public string TenMauThongTin
		{
			get
			{
				return this._TenMauThongTin;
			}
			set
			{
				if ((this._TenMauThongTin != value))
				{
					this.OnTenMauThongTinChanging(value);
					this.SendPropertyChanging();
					this._TenMauThongTin = value;
					this.SendPropertyChanged("TenMauThongTin");
					this.OnTenMauThongTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinTrenHopDong", DbType="NVarChar(1000)")]
		public string ThongTinTrenHopDong
		{
			get
			{
				return this._ThongTinTrenHopDong;
			}
			set
			{
				if ((this._ThongTinTrenHopDong != value))
				{
					this.OnThongTinTrenHopDongChanging(value);
					this.SendPropertyChanging();
					this._ThongTinTrenHopDong = value;
					this.SendPropertyChanged("ThongTinTrenHopDong");
					this.OnThongTinTrenHopDongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiDung;
		
		private string _TenDangNhap;
		
		private string _MaDangNhap;
		
		private bool _Admin;
		
		private bool _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(int value);
    partial void OnMaNguoiDungChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMaDangNhapChanging(string value);
    partial void OnMaDangNhapChanged();
    partial void OnAdminChanging(bool value);
    partial void OnAdminChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangNhap", DbType="NChar(50)")]
		public string MaDangNhap
		{
			get
			{
				return this._MaDangNhap;
			}
			set
			{
				if ((this._MaDangNhap != value))
				{
					this.OnMaDangNhapChanging(value);
					this.SendPropertyChanging();
					this._MaDangNhap = value;
					this.SendPropertyChanged("MaDangNhap");
					this.OnMaDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit NOT NULL")]
		public bool Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhong;
		
		private int _MaLoaiPhong;
		
		private string _TenPhong;
		
		private bool _Status;
		
		private string _TinhTrangPhong;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
		private EntitySet<ChiSoThang> _ChiSoThangs;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(int value);
    partial void OnMaPhongChanged();
    partial void OnMaLoaiPhongChanging(int value);
    partial void OnMaLoaiPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnTinhTrangPhongChanging(string value);
    partial void OnTinhTrangPhongChanged();
    #endregion
		
		public Phong()
		{
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			this._ChiSoThangs = new EntitySet<ChiSoThang>(new Action<ChiSoThang>(this.attach_ChiSoThangs), new Action<ChiSoThang>(this.detach_ChiSoThangs));
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiPhong", DbType="Int NOT NULL")]
		public int MaLoaiPhong
		{
			get
			{
				return this._MaLoaiPhong;
			}
			set
			{
				if ((this._MaLoaiPhong != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiPhong = value;
					this.SendPropertyChanged("MaLoaiPhong");
					this.OnMaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangPhong", DbType="NVarChar(100)")]
		public string TinhTrangPhong
		{
			get
			{
				return this._TinhTrangPhong;
			}
			set
			{
				if ((this._TinhTrangPhong != value))
				{
					this.OnTinhTrangPhongChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangPhong = value;
					this.SendPropertyChanged("TinhTrangPhong");
					this.OnTinhTrangPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ThuePhong", Storage="_ThuePhongs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_ChiSoThang", Storage="_ChiSoThangs", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<ChiSoThang> ChiSoThangs
		{
			get
			{
				return this._ChiSoThangs;
			}
			set
			{
				this._ChiSoThangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_LoaiPhong", ThisKey="MaLoaiPhong", OtherKey="MaLoaiPhong", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._MaLoaiPhong = value.MaLoaiPhong;
					}
					else
					{
						this._MaLoaiPhong = default(int);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
		
		private void attach_ChiSoThangs(ChiSoThang entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_ChiSoThangs(ChiSoThang entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhToan")]
	public partial class ThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaThanhToan;
		
		private long _MaHopDong;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private System.Nullable<bool> _TinhTrangThanhToan;
		
		private System.Nullable<decimal> _TienCuocPhi;
		
		private System.Nullable<decimal> _TienPhiKhac;
		
		private System.Nullable<System.DateTime> _ThoiGianThanhToan;
		
		private string _GhiChu;
		
		private EntityRef<HopDong> _HopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhToanChanging(long value);
    partial void OnMaThanhToanChanged();
    partial void OnMaHopDongChanging(long value);
    partial void OnMaHopDongChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnTinhTrangThanhToanChanging(System.Nullable<bool> value);
    partial void OnTinhTrangThanhToanChanged();
    partial void OnTienCuocPhiChanging(System.Nullable<decimal> value);
    partial void OnTienCuocPhiChanged();
    partial void OnTienPhiKhacChanging(System.Nullable<decimal> value);
    partial void OnTienPhiKhacChanged();
    partial void OnThoiGianThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianThanhToanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ThanhToan()
		{
			this._HopDong = default(EntityRef<HopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhToan", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaThanhToan
		{
			get
			{
				return this._MaThanhToan;
			}
			set
			{
				if ((this._MaThanhToan != value))
				{
					this.OnMaThanhToanChanging(value);
					this.SendPropertyChanging();
					this._MaThanhToan = value;
					this.SendPropertyChanged("MaThanhToan");
					this.OnMaThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangThanhToan", DbType="Bit")]
		public System.Nullable<bool> TinhTrangThanhToan
		{
			get
			{
				return this._TinhTrangThanhToan;
			}
			set
			{
				if ((this._TinhTrangThanhToan != value))
				{
					this.OnTinhTrangThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangThanhToan = value;
					this.SendPropertyChanged("TinhTrangThanhToan");
					this.OnTinhTrangThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienCuocPhi", DbType="Money")]
		public System.Nullable<decimal> TienCuocPhi
		{
			get
			{
				return this._TienCuocPhi;
			}
			set
			{
				if ((this._TienCuocPhi != value))
				{
					this.OnTienCuocPhiChanging(value);
					this.SendPropertyChanging();
					this._TienCuocPhi = value;
					this.SendPropertyChanged("TienCuocPhi");
					this.OnTienCuocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhiKhac", DbType="Money")]
		public System.Nullable<decimal> TienPhiKhac
		{
			get
			{
				return this._TienPhiKhac;
			}
			set
			{
				if ((this._TienPhiKhac != value))
				{
					this.OnTienPhiKhacChanging(value);
					this.SendPropertyChanging();
					this._TienPhiKhac = value;
					this.SendPropertyChanged("TienPhiKhac");
					this.OnTienPhiKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianThanhToan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianThanhToan
		{
			get
			{
				return this._ThoiGianThanhToan;
			}
			set
			{
				if ((this._ThoiGianThanhToan != value))
				{
					this.OnThoiGianThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianThanhToan = value;
					this.SendPropertyChanged("ThoiGianThanhToan");
					this.OnThoiGianThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ThanhToan", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.ThanhToans.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.ThanhToans.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(long);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiuCuocPhi")]
	public partial class ChiuCuocPhi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaHopDong;
		
		private int _MaCuocPhi;
		
		private int _SoLuong;
		
		private EntityRef<CuocPhi> _CuocPhi;
		
		private EntityRef<HopDong> _HopDong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(long value);
    partial void OnMaHopDongChanged();
    partial void OnMaCuocPhiChanging(int value);
    partial void OnMaCuocPhiChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    #endregion
		
		public ChiuCuocPhi()
		{
			this._CuocPhi = default(EntityRef<CuocPhi>);
			this._HopDong = default(EntityRef<HopDong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HopDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCuocPhi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCuocPhi
		{
			get
			{
				return this._MaCuocPhi;
			}
			set
			{
				if ((this._MaCuocPhi != value))
				{
					if (this._CuocPhi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCuocPhiChanging(value);
					this.SendPropertyChanging();
					this._MaCuocPhi = value;
					this.SendPropertyChanged("MaCuocPhi");
					this.OnMaCuocPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuocPhi_ChiuCuocPhi", Storage="_CuocPhi", ThisKey="MaCuocPhi", OtherKey="MaCuocPhi", IsForeignKey=true)]
		public CuocPhi CuocPhi
		{
			get
			{
				return this._CuocPhi.Entity;
			}
			set
			{
				CuocPhi previousValue = this._CuocPhi.Entity;
				if (((previousValue != value) 
							|| (this._CuocPhi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuocPhi.Entity = null;
						previousValue.ChiuCuocPhis.Remove(this);
					}
					this._CuocPhi.Entity = value;
					if ((value != null))
					{
						value.ChiuCuocPhis.Add(this);
						this._MaCuocPhi = value.MaCuocPhi;
					}
					else
					{
						this._MaCuocPhi = default(int);
					}
					this.SendPropertyChanged("CuocPhi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ChiuCuocPhi", Storage="_HopDong", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HopDong HopDong
		{
			get
			{
				return this._HopDong.Entity;
			}
			set
			{
				HopDong previousValue = this._HopDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDong.Entity = null;
						previousValue.ChiuCuocPhis.Remove(this);
					}
					this._HopDong.Entity = value;
					if ((value != null))
					{
						value.ChiuCuocPhis.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(long);
					}
					this.SendPropertyChanged("HopDong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDong")]
	public partial class HopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaHopDong;
		
		private System.DateTime _NgayThue;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private System.Nullable<System.DateTime> _NgayLamHopDong;
		
		private System.Nullable<decimal> _TienCoc;
		
		private System.Nullable<decimal> _GiaThue;
		
		private System.Nullable<long> _ChiSoDien;
		
		private System.Nullable<long> _ChiSoNuoc;
		
		private string _GhiChu;
		
		private bool _Status;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
		private EntitySet<ThanhToan> _ThanhToans;
		
		private EntitySet<ChiuCuocPhi> _ChiuCuocPhis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(long value);
    partial void OnMaHopDongChanged();
    partial void OnNgayThueChanging(System.DateTime value);
    partial void OnNgayThueChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnNgayLamHopDongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLamHopDongChanged();
    partial void OnTienCocChanging(System.Nullable<decimal> value);
    partial void OnTienCocChanged();
    partial void OnGiaThueChanging(System.Nullable<decimal> value);
    partial void OnGiaThueChanged();
    partial void OnChiSoDienChanging(System.Nullable<long> value);
    partial void OnChiSoDienChanged();
    partial void OnChiSoNuocChanging(System.Nullable<long> value);
    partial void OnChiSoNuocChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public HopDong()
		{
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			this._ThanhToans = new EntitySet<ThanhToan>(new Action<ThanhToan>(this.attach_ThanhToans), new Action<ThanhToan>(this.detach_ThanhToans));
			this._ChiuCuocPhis = new EntitySet<ChiuCuocPhi>(new Action<ChiuCuocPhi>(this.attach_ChiuCuocPhis), new Action<ChiuCuocPhi>(this.detach_ChiuCuocPhis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThue", DbType="DateTime NOT NULL")]
		public System.DateTime NgayThue
		{
			get
			{
				return this._NgayThue;
			}
			set
			{
				if ((this._NgayThue != value))
				{
					this.OnNgayThueChanging(value);
					this.SendPropertyChanging();
					this._NgayThue = value;
					this.SendPropertyChanged("NgayThue");
					this.OnNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamHopDong", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLamHopDong
		{
			get
			{
				return this._NgayLamHopDong;
			}
			set
			{
				if ((this._NgayLamHopDong != value))
				{
					this.OnNgayLamHopDongChanging(value);
					this.SendPropertyChanging();
					this._NgayLamHopDong = value;
					this.SendPropertyChanged("NgayLamHopDong");
					this.OnNgayLamHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienCoc", DbType="Money")]
		public System.Nullable<decimal> TienCoc
		{
			get
			{
				return this._TienCoc;
			}
			set
			{
				if ((this._TienCoc != value))
				{
					this.OnTienCocChanging(value);
					this.SendPropertyChanging();
					this._TienCoc = value;
					this.SendPropertyChanged("TienCoc");
					this.OnTienCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="Money")]
		public System.Nullable<decimal> GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this.OnGiaThueChanging(value);
					this.SendPropertyChanging();
					this._GiaThue = value;
					this.SendPropertyChanged("GiaThue");
					this.OnGiaThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoDien", DbType="BigInt")]
		public System.Nullable<long> ChiSoDien
		{
			get
			{
				return this._ChiSoDien;
			}
			set
			{
				if ((this._ChiSoDien != value))
				{
					this.OnChiSoDienChanging(value);
					this.SendPropertyChanging();
					this._ChiSoDien = value;
					this.SendPropertyChanged("ChiSoDien");
					this.OnChiSoDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoNuoc", DbType="BigInt")]
		public System.Nullable<long> ChiSoNuoc
		{
			get
			{
				return this._ChiSoNuoc;
			}
			set
			{
				if ((this._ChiSoNuoc != value))
				{
					this.OnChiSoNuocChanging(value);
					this.SendPropertyChanging();
					this._ChiSoNuoc = value;
					this.SendPropertyChanged("ChiSoNuoc");
					this.OnChiSoNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ThuePhong", Storage="_ThuePhongs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ThanhToan", Storage="_ThanhToans", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<ThanhToan> ThanhToans
		{
			get
			{
				return this._ThanhToans;
			}
			set
			{
				this._ThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDong_ChiuCuocPhi", Storage="_ChiuCuocPhis", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<ChiuCuocPhi> ChiuCuocPhis
		{
			get
			{
				return this._ChiuCuocPhis;
			}
			set
			{
				this._ChiuCuocPhis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
		
		private void attach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
		
		private void attach_ChiuCuocPhis(ChiuCuocPhi entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = this;
		}
		
		private void detach_ChiuCuocPhis(ChiuCuocPhi entity)
		{
			this.SendPropertyChanging();
			entity.HopDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khach")]
	public partial class Khach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaKhach;
		
		private string _TenKhach;
		
		private System.DateTime _NgaySinh;
		
		private bool _GioiTinh;
		
		private string _SoDinhDanh;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private string _Hinh;
		
		private System.Nullable<bool> _TinhTrangHonNhan;
		
		private System.Nullable<bool> _DangKyTamTru;
		
		private bool _Status;
		
		private EntitySet<ThuePhong> _ThuePhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachChanging(long value);
    partial void OnMaKhachChanged();
    partial void OnTenKhachChanging(string value);
    partial void OnTenKhachChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(bool value);
    partial void OnGioiTinhChanged();
    partial void OnSoDinhDanhChanging(string value);
    partial void OnSoDinhDanhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnTinhTrangHonNhanChanging(System.Nullable<bool> value);
    partial void OnTinhTrangHonNhanChanged();
    partial void OnDangKyTamTruChanging(System.Nullable<bool> value);
    partial void OnDangKyTamTruChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public Khach()
		{
			this._ThuePhongs = new EntitySet<ThuePhong>(new Action<ThuePhong>(this.attach_ThuePhongs), new Action<ThuePhong>(this.detach_ThuePhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhach", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaKhach
		{
			get
			{
				return this._MaKhach;
			}
			set
			{
				if ((this._MaKhach != value))
				{
					this.OnMaKhachChanging(value);
					this.SendPropertyChanging();
					this._MaKhach = value;
					this.SendPropertyChanged("MaKhach");
					this.OnMaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhach", DbType="NVarChar(50)")]
		public string TenKhach
		{
			get
			{
				return this._TenKhach;
			}
			set
			{
				if ((this._TenKhach != value))
				{
					this.OnTenKhachChanging(value);
					this.SendPropertyChanging();
					this._TenKhach = value;
					this.SendPropertyChanged("TenKhach");
					this.OnTenKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit NOT NULL")]
		public bool GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDinhDanh", DbType="NChar(12)")]
		public string SoDinhDanh
		{
			get
			{
				return this._SoDinhDanh;
			}
			set
			{
				if ((this._SoDinhDanh != value))
				{
					this.OnSoDinhDanhChanging(value);
					this.SendPropertyChanging();
					this._SoDinhDanh = value;
					this.SendPropertyChanged("SoDinhDanh");
					this.OnSoDinhDanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(150)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="VarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangHonNhan", DbType="Bit")]
		public System.Nullable<bool> TinhTrangHonNhan
		{
			get
			{
				return this._TinhTrangHonNhan;
			}
			set
			{
				if ((this._TinhTrangHonNhan != value))
				{
					this.OnTinhTrangHonNhanChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangHonNhan = value;
					this.SendPropertyChanged("TinhTrangHonNhan");
					this.OnTinhTrangHonNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangKyTamTru", DbType="Bit")]
		public System.Nullable<bool> DangKyTamTru
		{
			get
			{
				return this._DangKyTamTru;
			}
			set
			{
				if ((this._DangKyTamTru != value))
				{
					this.OnDangKyTamTruChanging(value);
					this.SendPropertyChanging();
					this._DangKyTamTru = value;
					this.SendPropertyChanged("DangKyTamTru");
					this.OnDangKyTamTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_ThuePhong", Storage="_ThuePhongs", ThisKey="MaKhach", OtherKey="MaKhach")]
		public EntitySet<ThuePhong> ThuePhongs
		{
			get
			{
				return this._ThuePhongs;
			}
			set
			{
				this._ThuePhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Khach = this;
		}
		
		private void detach_ThuePhongs(ThuePhong entity)
		{
			this.SendPropertyChanging();
			entity.Khach = null;
		}
	}
}
#pragma warning restore 1591
